# Generated by Django 5.0.2 on 2024-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=100)),
                ('hotelimage', models.ImageField(upload_to='hotel_images/')),
                ('descriptions', models.TextField()),
                ('totalroom', models.IntegerField()),
                ('roommap', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('dateadded', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomimage',
            field=models.ImageField(upload_to='room_images/'),
        ),
    ]
