# Generated by Django 5.0.2 on 2024-03-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='todo.hotels'),
            preserve_default=False,
        ),
    ]
