# Generated by Django 5.0.2 on 2024-03-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rooms_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('total', models.IntegerField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('processing', 'Processing')], default='processing', max_length=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.hotels')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.rooms')),
            ],
        ),
    ]
