# Generated by Django 5.0.2 on 2024-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.IntegerField(),
        ),
    ]
