# Generated by Django 5.0.2 on 2024-03-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_booking_phonenumber_alter_booking_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='id',
            new_name='roomid',
        ),
    ]
