# Generated by Django 5.0.2 on 2024-03-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
