# Generated by Django 5.0.2 on 2024-03-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_booking_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='id',
            new_name='hotel_id',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='roomid',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='todo.users'),
            preserve_default=False,
        ),
    ]
