# Generated by Django 5.0.2 on 2024-03-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_rename_user_id_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
