# Generated by Django 5.0.2 on 2024-03-20 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_users_groups_users_is_superuser_users_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
