# Generated by Django 5.0.2 on 2024-03-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_users_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
