# Generated by Django 5.0.2 on 2024-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_users_is_active_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processing', 'Processing'), ('hide', 'Hide')], default='processing', max_length=10),
        ),
    ]
