# Generated by Django 5.0.3 on 2024-04-02 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='datebooking',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
