# Generated by Django 5.0.3 on 2024-04-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_rooms_roomimage_delete_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='status',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('simple_room', 'Simple Room'), ('double_room', 'Double Room'), ('family_room', 'Family Room')], default=str, max_length=20),
            preserve_default=False,
        ),
    ]
