# Generated by Django 5.0.3 on 2024-04-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_remove_rooms_status_rooms_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('descriptions', models.TextField()),
                ('rating', models.IntegerField()),
                ('datecommented', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
